<div class="all">
    <div class="assetEdit-tabTable-metadata-header">
        <div class="assetlist-assetMenu-refresh">
            <label>
                REFRESH
            </label>
            <img id="siteListRefresh" src="images/common/refresh.png" class="gwt-Image" />
        </div>
        <?php if(!empty($this->acl->resources["admin-site-add"]) && (
                    (empty($this->acl->resources["admin-site-add"]) ) ||
                    (!empty($this->acl->resources["admin-site-add"]) 
                        && count($this->entity) < $this->acl->resources["admin-site-limit"] ) ) ):?> 
            <button id="siteListAdd" class="connectorlist-header-add" type="button">
            </button>
        <?php endif;?>
    </div><!-- cierre assetEdit-tabTable-metadata-header -->
    <table id="siteListTable" class="display dataTable" border="0" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th style="width: 200px;">NAME</th>
                <th style="width: 200px;">DOMAIN</th>
                <th style="width: 150px;">PLAYLIST</th>
                <th style="width: 200px;">DATE</th>
                <th style="width: 100px;">EDIT/DELETE</th>
            </tr>
        </thead>
    </table>
</div><!-- cierre all -->
<div id="siteDeleteDialog">
</div>
<script type="text/javascript" charset="utf-8">
    $(document).ready( function() {
        HB2.admin.site.list();
    });
</script>