<script src="/js/jquery/jquery.json-2.2.min.js" type="text/javascript"></script>
<div class="all">
    <div class="hb-tabTable-metadata-header">
        <div class="hb-refresh">
            <label>
                REFRESH
            </label>
            <img id="refresh" src="images/common/refresh.png" class="gwt-Image" />
        </div>
        </button>
    </div><!-- cierre assetEdit-tabTable-metadata-header -->
    <table id="processTable" class="display dataTable" border="0" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th style="width: 200px;">ID</th>
                <th style="width: 50px;">TYPE</th>
                <th style="width: 200px;">STATUS</th>
                <th style="width: 200px;">DATE</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    <div class="clear"></div>
</div><!-- cierre all -->
<script type="text/javascript" charset="utf-8">

    function initProcessTableData(table, objs) {
        table.fnClearTable();
        var datas = new Array();
        for (i in objs) {
            var data = new Array();
            data[0] = objs[i].id;
            data[1] = objs[i].type;
            data[2] = objs[i].status;
            data[3] = objs[i].created;
            datas[i] = data;
        }
        table.fnAddData(datas);
    }

    function loadProcesses(table) {
        $.ajax({
            url: '/process/find',
            dataType: 'json',
            success: function(data, textStatus, jqXHR) {
                console.log(data);
                initProcessTableData(table, data.result);
            }
        } );
    }
    $(document).ready( function() {
        // Init Connectors Table
        var table = $('#processTable').dataTable({
            "bLengthChange": false,
            "aoColumnDefs": [{
                "bVisible": false,
                "aTargets": [ 0 ]
            },{
                "sClass": "center",
                "aTargets": [ 1, 2, 3 ]
            }]
        });

        // Refresh Connectors Button
        $('#refresh').click( function() {
            loadProcesses(table);
        });
        // Load Connectors
        loadProcesses(table);
        table[0].style.width = '100%';
    });
</script>