<div class="anonymous-wrapper">
    <div class="anonymous-all">
        <div class="anonymous-nopermission">
            <img src="/images/anonymous/img_info.png" alt="Info"/>
            <div class="anonymous-nopermission-info">
                SORRY!
            </div>
            <div class="anonymous-nopermission-msg">
                You haven’t permissions for this site,
                please register now! or leave this site, thanks.
            </div>
            <div class="anonymous-register-submit">
                <a href="/auth/registry">
                <button class="anonymous-register-submit-btn" name="btnSubmit" id="btnSubmit" type="button">
                </button>
                </a>
            </div>
            <div class="anonymous-register-hollybyte">
                <img src="/images/anonymous/img_hollybyte.png" alt="Hollybyte"/>
            </div>
            <div class="clear">
            </div>
        </div><!--cierre anonymous-login-->
    </div> <!-- cierre home-all -->
</div> <!-- cierre home-wrapper -->