<div class="hb-assetform-tabTable-profiles" id="tabProfilesContent">
    <div class="hb-assetform-tabTable-metadata-header">
        <div class="hb-assetform-tabTable-metadata-header-title">
            <img src="/images/assetedit/ico_profiles.png" class="hb-assetform-tabTable-metadata-header-title-ico" />
            <div class="hb-assetform-tabTable-metadata-header-title-lbl">
                ENCODING PROFILES
            </div>
            <a class="hb-assetform-tabTable-metadata-header-title-help"></a>
        </div>
    </div>
    <table id="contentsTable" class="display dataTable" border="0" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th style="width: 210px; text-align: center">NAME</th>
                <th style="width: 110px; text-align: center">TYPE</th>
                <th style="width: 143px; text-align: center">FORMAT</th>
                <th></th><!-- PATH -->
                <th style="width: 136px; text-align: center">REENCODE/DOWNLOAD</th>
            </tr>
        </thead>
    </table>
</div>
