<div class="hb-assetform-tabTable-publish" id="tabPublishContent">
    <div class="hb-assetform-tabTable-metadata-header">
        <div class="hb-assetform-tabTable-metadata-header-title">
            <img src="/images/assetedit/ico_profiles.png" class="hb-assetform-tabTable-metadata-header-title-ico" />
            <div class="hb-assetform-tabTable-metadata-header-title-lbl">
                GROUPS
            </div>
            <a class="hb-assetform-tabTable-metadata-header-title-help"></a>
        </div>
    </div><!-- cierre assetEdit-tabTable-metadata-header -->
    <table id="groupsTable" class="display dataTable" border="0" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th style="width: 90px; text-align: center">NAME</th>
                <th style="width: 120px; text-align: center">TYPE</th>
                <th></th><!-- PATH -->
                <th style="width: 186px; text-align: center">CONTENTS</th>
                <th style="width: 150px; text-align: center">SMIL</th>
            </tr>
        </thead>
    </table>
</div><!-- cierre assetEdit-tabTable-publish -->
