<div class="HB-Connector-Edit">
    <div class="HB-Connector-Menu">
        <div class="HB-Connector-Menu-Content">
            <div class="HB-Connector-Crumbs">
                <div class="HB-Connector-Crumbs-Before">
                    EDIT CONNECTOR
                </div>
                <img src="/images/common/crumb.png" class="HB-Connector-Crumb" />
                <div class="HB-Connector-Crumbs-Current"></div>
            </div>
        </div>
    </div>
    <div class="HB-Connector-Edit-Content">
        <div class="HB-Connector-Edit-Left">
            <div class="HB-Connector-Edit-Left-Item">
                <img id="connectorSave" src="/images/common/save.png" />
            </div>
            <div class="HB-Connector-Edit-Left-Item">
                <img id="connectorClear" src="/images/common/clear.png" />
            </div>
            <div class="HB-Connector-Edit-Left-Item">
                <img id="connectorBack" src="/images/common/back.png" />
            </div>
        </div>
        <div class="connectorEdit-right">
            <form id="connectorForm">
                <div class="HB-Connector-Edit-Form-Box">
                    <label for="id">
                        NAME</label>
                    <input id="id" name="id" class="HB2-Connector-Edit-Form-Box-Txt" type="text">
                </div>
                <div class="HB-Connector-Edit-Form-Box">
                    <label for="description">
                        DESCRIPTION</label>
                    <textarea id="description" name="description" class="HB2-Connector-Edit-Form-Box-Area"></textarea>
                </div>
                <div class="HB-Connector-Edit-Form-Box">
                    <label>
                        TYPE</label>
                    <select id="type" name="type" class="gwt-ListBox">
                        <option value="FTP">FTP</option>
                        <option value="YOUTUBE">Youtube</option>
                        <option value="TWITTER">Twitter</option>
                        <option value="FACEBOOK">Facebook</option>
                    </select>
                </div>
                <div class="HB-Connector-Edit-Form-Box">
                    <div id="usernameLayer">
                        <label for="username">
                            USERNAME</label>
                        <input id="username" name="username" class="HB-Connector-Edit-Form-Box-Txt" type="text" />
                    </div>
                    <div id="passwordLayer">
                        <label>
                            PASSWORD</label>
                        <input id="password" name="password" class="HB-Connector-Edit-Form-Box-Txt" type="password" />
                    </div>
                    <div id="serverLayer">
                        <label for="server">
                            SERVER</label>
                        <input id="server" name="server" class="connectorEdit-right-element-txt" type="text" />
                    </div>
                    <div id="portLayer">
                        <label for="port">
                            PORT</label>
                        <input id="port" name="port" class="connectorEdit-right-element-txt" type="text" value="21">
                        </input>
                    </div>
                    <div id="directoryLayer">
                        <label for="dir">
                            DIRECTORY</label>
                        <input id="dir" name="dir" class="connectorEdit-right-element-txt" type="text" />
                    </div>
                </div>
                <input id="created" name="created" type="hidden" />
                <input id="version" name="version" type="hidden" />
            </form>
            <div class="test-buttom" style="display: none;">
                <a href="" id="testBt">
                <img src="/images/connector/grant_permissions.png" alt="TEST BUTTOM" />
                </a>
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>
<script type="text/javascript" charset="utf-8">
$(document).ready( function() {
<?php if(isset($this->entity)): ?>var entity = jQuery.parseJSON('<?php echo json_encode($this->entity) ?>');<?php else:?>
    var entity = {};
<?php endif;?>
    // Init Connector Edit
    HB2.admin.initConnectorEdit(entity);
    });
</script>
