<script src="/js/jquery/jquery.json-2.2.min.js" type="text/javascript"></script>
<script src="/js/jquery/jquery.iframe-post-form.min.js" type="text/javascript"></script>
<div class="all">
    <div class="HB-Connector-Top">
        <div class="HB-Connector-Refresh">
            <label>
                REFRESH
            </label>
            <img id="refresh" src="images/common/refresh.png" />
        </div>
        <?php if(!empty($this->acl->resources["admin-connector-add"]) && (
                    (empty($this->acl->resources["admin-connector-add"]) ) ||
                    (!empty($this->acl->resources["admin-connector-add"]) 
                        && count($this->entity) < $this->acl->resources["admin-connector-limit"] ) ) ):?> 
        <button id="add" class="HB-Connector-Add" type="button"></button>
        <?php endif;?>
    </div><!-- cierre assetEdit-tabTable-metadata-header -->
    <table id="connectorTable" class="display dataTable" border="0" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th style="width: 200px;" class="sorting">NAME</th>
                <th style="width: 50px;" class="sorting">TYPE</th>
                <th style="width: 200px;" class="sorting">DESC</th>
                <th style="width: 200px;" class="sorting">DATE</th>
                <th style="width: 100px;" class="sorting">EDIT/DELETE</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    <div class="clear"></div>
</div><!-- cierre all -->
<div id="deleteDialog" title="Delete Connector?">
    <p>
        <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>These items will be permanently deleted and cannot be recovered. Are you sure?
    </p>
</div>
<script type="text/javascript" charset="utf-8">
    $(document).ready( function() {
        HB2.admin.connector.initIndex();
    });
</script>