<div class="HB-Playlist-Tab-Asset" id="tabAssetContent">
    <div class="HB-Playlist-Asset" >
        <div class="HB-Playlist-Asset-Menu">
            <div class="HB-Playlist-Asset-Menu-Label">LISTADO DE ASSETS</div>
            <div class="HB-Playlist-Asset-Actions">
                <button id="add-asset-button" class="HB-Playlist-Asset-Add" type="button"></button>
                <button id="btn-top" class="HB-Playlist-Asset-Actions-Top" type="button"></button>
                <button id="btn-up" class="HB-Playlist-Asset-Actions-Up" type="button"></button>
                <button id="btn-down" class="HB-Playlist-Asset-Actions-Down" type="button"></button>
                <button id="btn-bottom" class="HB-Playlist-Asset-Actions-Bottom" type="button"></button>
            </div>
            <table class="display dataTable" border="0" cellpadding="0" cellspacing="0" id="assetTable">
                <thead>
                    <tr>
                        <th style="width: 10px; text-align: center;"></th>
                        <th style="width: 90px; text-align: center;"></th>
                        <th style="width: 450px; text-align: center;"></th>
                        <th style="width: 10px; text-align: center;"></th>
                        <th style="width: 10px; text-align: center;"></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div id="addAssetDialog" title="Add Asset" class="jDialog">
    <table class="display dataTable" border="0" cellpadding="0" cellspacing="0" id="addAssetTable">
        <thead>
            <tr>
                <th style="width: 20px; text-align: center"></th>
                <th style="width: 60px; text-align: center"></th>
                <th style="width: 600px; text-align: center"></th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>