<div class="hb-assetform-tabTable-general" id="tabGeneralContent">
    <div class="hb-assetform-tabTable-general-left">
        <input type="hidden" id="assetSplash" />
        <div class="hb-assetform-tabTable-general-left-img">
            <a id="assetPlayer" style="display:block;width:100%;height:100%;">
            <img  id="playerSplash" class="player-splash" />
            <img src="/images/common/play.png" alt="Play" class="player-play" />
            </a>
        </div>
        <div class="hb-assetform-tabTable-general-left-newthumbnail">
            <div class="hb-assetform-tabTable-general-left-newthumbnail-lbl">
                SNAPSHOT <img src="/images/assetedit/btn_thumbnail.png" id="assetSnapshot"/>
            </div>
            <a class="hb-assetform-tabTable-general-left-newthumbnail-help" title="Seleccione un snapshot"></a>
        </div>
        <div class="hb-assetform-tabTable-general-left-newthumbnail">
            <div class="hb-assetform-tabTable-general-left-newthumbnail-lbl">
               UPLOAD YOUR OWN THUMBNAIL
            </div>
            <a class="hb-assetform-tabTable-general-left-newthumbnail-help"  title="Upload your custom snapshot"></a>
        </div>
        <div class="hb-assetform-tabTable-general-left-upload">
        </div>
        <div class="hb-assetform-tabTable-general-left-info">
            Choose a file to upload.
            <br />
            * Fields are required
        </div>      
        <div class="upld-form-elements">
            <input id="assetSplashUpload" name="assetSplashUpload" size="40" type="file" />
            <input id="assetSplashValue" name="assetSplashValue" type="hidden" />
            <input class="submit" type="submit" name="assetSplashUploadBtn" id="assetSplashUploadBtn" value="Send"/>
        </div>
    </div>
    <div class="hb-assetform-tabTable-general-right">
        <div class="hb-assetform-tabTable-general-right-info">
            <img src="/images/assetedit/ico_info.png" class=
            "hb-assetform-tabTable-general-right-info-ico" alt="Image" />
            <div class="hb-assetform-tabTable-general-right-info-lbl">
                GENERAL INFO
            </div>
            <a class="hb-assetform-tabTable-general-right-info-help"></a>
        </div>
        <div class="hb-assetform-tabTable-general-right-info">
            <div class="hb-assetform-tabTable-general-right-info-title">
                ID
            </div>
            <div class="hb-assetform-tabTable-general-right-info-lbl2">
                <span id="assetId"></span>
            </div>
            <a class="hb-assetform-tabTable-general-right-info-help"></a>
        </div>
        <div class="hb-assetform-tabTable-general-right-formbox">
            <div class="hb-assetform-tabTable-general-right-formbox-lbl">
                <span class="gwt-InlineHTML">NAME*</span>
            </div>
            <input class="hb-assetform-tabTable-general-right-formbox-txt" type="text" name="assetName" value="" id="assetName"/>
        </div>
        <div class="hb-assetform-tabTable-general-right-formbox">
            <div class="hb-assetform-tabTable-general-right-formbox-lbl">
                <span class="gwt-InlineHTML">TITTLE*</span>
            </div>
            <input class="hb-assetform-tabTable-general-right-formbox-txt" type="text" name="assetTitle" value="" id="assetTitle"/>
        </div>
        <div class="hb-assetform-tabTable-general-right-formbox">
            <div class="hb-assetform-tabTable-general-right-formbox-lbl">
                <span class="gwt-InlineHTML">DESCRIPTION*</span>
            </div>
            <textarea class="hb-assetform-tabTable-general-right-formbox-area" name="assetDescription" id="assetDescription"></textarea>
        </div>
        <div class="hb-assetform-tabTable-publish-table-content-grey-createtime">
            <div class="hb-assetform-tabTable-general-right-formbox-lbl">
                <span class="gwt-InlineHTML">CREATED</span>
            </div>
            <div class="hb-assetform-tabTable-general-right-formbox-lbl2">
                <span class="gwt-InlineHTML">UPDATED</span>
            </div>
            <div class="clear"></div>
            <input class="hb-assetform-tabTable-publish-table-content-grey-date" type="text" name="assetCreated" id="assetCreated" />
            <input class="hb-assetform-tabTable-publish-table-content-grey-date" type="text" name="assetUpdated" id="assetUpdated" />
            <div class="clear">
            </div>
        </div>
        <!-- <span class="hb-assetform-tabTable-publishvalue"><input tabindex="0" id="gwt-uid-105" value="on" type="checkbox" /></span>-->
    </div><!-- cierre assetEdit-tabTable-general-right -->
</div><!-- cierre assetEdit-tabTable-general -->
