<script src="/js/jquery/jquery.json-2.2.min.js" type="text/javascript"></script>
<script src="/js/jquery/jquery.iframe-post-form.min.js" type="text/javascript"></script>
<div class="all">
    <div class="assetEdit-tabTable-metadata-header">
        <div class="assetlist-assetMenu-refresh">
            <label>
                REFRESH
            </label>
            <img id="refresh" src="images/common/refresh.png" />
        </div>
        <?php if (!empty($this->acl->resources["admin-player-add"])): ?>
            <?php if (empty($this->acl->resources["admin-player-limit"])): ?>
                <img id="add" src="http://hollybyte.s3.amazonaws.com/sites/admin/img/common/add.png" />
            <?php else: ?>
            <?php if(count($this->entity) < $this->acl->resources["admin-player-limit"]) ?>
                <img id="add" src="http://hollybyte.s3.amazonaws.com/sites/admin/img/common/add.png" />
            <?php endif; ?>
        <?php endif; ?>
        </button>
    </div>
    <table id="playerTable" class="display dataTable" border="0" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th style="width: 200px;">NAME</th>
                <th style="width: 50px;">TYPE</th>
                <th style="width: 200px;">PLAYER</th>
                <th style="width: 200px;">DATE</th>
                <?php if( empty($this->acl->resources["admin-player-btn-update"]) && empty($this->acl->resources["admin-player-btn-delete"]) ) : ?>
                    
                <?php else:?>
                    <th style="width: 100px;">EDIT/DELETE</th>
                <?php endif; ?>
                
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    <div class="clear"></div>
</div><!-- cierre all -->
<div id="deleteDialog" title="Delete Player?">
    <p>
        <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>These items will be permanently deleted and cannot be recovered. Are you sure?
    </p>
</div>
<script type="text/javascript" charset="utf-8">
    function onClickEditPlayer(element, table) {
        var id = table.fnGetData($(element).parents('tr')[0])[0];
        window.location = '/player/form?id='+id;
    }

    function onClickDeletePlayer(element, table) {
        var pos = table.fnGetPosition($(element).parents('tr')[0]);
        var data = table.fnGetData(pos);
        $(table).data('position', pos);
        $(table).data('data', data);
        $("#deleteDialog").dialog('open');
    }

    function initPlayersTable(table, objs) {
        table.fnClearTable();
        var rows = new Array();
        for (var i = 0; i < objs.length; i++) {
            var row = new Array();
            row[0] = objs[i].id;
            row[1] = objs[i].type;
            row[2] = objs[i].player;
            row[3] = objs[i].created;
            
            if(HB2.admin.allowed('admin-player-btn-update') || HB2.admin.allowed('admin-player-btn-delete' ) ){
                row[4] = '';
            }
            if(HB2.admin.allowed('admin-player-btn-update')  ){
               
                row[4] += '<img class="player-edit" src="/images/common/edit.png" />';
            }
            if(HB2.admin.allowed('admin-player-btn-delete')  &&  (objs[i].id  !== 'default-flash')  && (objs[i].id !== 'default-html5') ){
                
                row[4] += '<img class="player-delete" src="/images/common/delete.png"/>';
            }
            rows[i] = row;
        }
        table.fnAddData(rows);

        $('.player-edit').click( function() {
            onClickEditPlayer(this, table);
        });
        $('.player-delete').click( function() {
            onClickDeletePlayer(this, table);
        });
    }

    function loadPlayers(table, data) {
        if(data){
            initPlayersTable(table, data);
            return;
        }
        $.ajax({
            url: '/player/find',
            dataType: 'json',
            success: function(data, textStatus, jqXHR) {
                initPlayersTable(table, data.result);
            }
        } );
    }

    function deletePlayer(id) {
        console.log('deletePlayer: '+id);
        $.ajax({
            url: '/player/delete?id='+id,
            dataType: 'json',
            success: function(data, textStatus, jqXHR) {
                console.info(data);
            }
        } );
    }

    $(document).ready( function() {
        // Init Players Table
        var table = $('#playerTable').dataTable({
            "bLengthChange": false,
            "aoColumnDefs": [{
                "sClass": "center",
                "aTargets": [ 1 ]
            }]
        });

        // Init Delete Dialog
        $('#deleteDialog').dialog({
            autoOpen: false,
            resizable: false,
            height:260,
            modal: true,
            buttons: {
                "Delete item": function() {
                    var pos = table.data('position');
                    var data = table.data('data');
                    deletePlayer(data[0]);
                    table.fnDeleteRow(pos);
                    $(this).dialog("close");
                },
                Cancel: function() {
                    $(this).dialog("close");
                }
            }
        });

        // Refresh Players Button
        $('#refresh').click( function() {
            loadPlayers(table);
        });
        // Add Player Button
        $('#add').click( function() {
            window.location = '/player/form';
        });
        // Load Players
        
        loadPlayers(table, <?php echo json_encode($this->entity); ?>);
    });
</script>