
   <a
         href="<?php echo $this->repo?>/<?php echo $this->asset->source->path;?>"
         style="display:block;width:100%;height:100%; "
         id="player"
    >
    	<img src="<?php echo $this->repo?>/<?php echo $this->asset->splash;?>" class="player-splash"/>
    	<img src="/images/common/play.png" alt="Play" class="player-play"/>
   </a>

               
               
               
               
<script>
	flowplayer("player", "/swf/flowplayer.commercial-3.2.6.1.swf",{
		key: '#@0b3272bb43eff43967a',
		play: {
			url: 'http://elplanb.s3.amazonaws.com/accounts/elplanb/site/images/player/play.png',
			width: 78,
			height: 78
		},
		clip: {
			
			autoPlay: true,
			
			autoBuffering: true
		},
		plugins: {
			"controls" : {
				"url": "http://repo.eu-w1.hollybyte.com/public/players/flowplayer/swf/flowplayer-3.2.7.swf",
				"autoHide" :
				{
					"enabled" : true,
					"fullscreenOnly" : false,
					"hideDelay" : 1019,
					"hideDuration" : 887,
					"hideStyle" : "move",
					"mouseOutDelay" : 500
				},
				"backgroundColor" : "rgba(46, 46, 46, 0)",
				"backgroundGradient" : "none",
				"border" : "0px",
				"borderColor" : "rgba(0, 0, 0, 1)",
				"borderRadius" : 30,
				"borderWidth" : 0,
				"bottom" : 0,
				"bufferColor" : "rgba(33, 33, 33, 1)",
				"bufferGradient" : "none",
				"builtIn" : false,
				"buttonColor" : "#ffffff",
				"buttonOverColor" : "rgba(41, 41, 41, 1)",
				"display" : "block",
				"durationColor" : "rgba(0, 153, 255, 1)",
				"fastBackward" : false,
				"fastForward" : true,
				"fullscreen" : true,
				"height" : 36,
				"left" : "50pct",
				"margins" : [ 2,
					6,
					2,
					12
				  ],
				"mute" : true,
				"name" : "controls",
				"opacity" : 1,
				"play" : true,
				"playlist" : false,
				"progressColor" : "rgba(0, 153, 255, 1)",
				"progressGradient" : "none",
				"scrubber" : true,
				"scrubberBarHeightRatio" : 1,
				"scrubberHeightRatio" : 0.5,
				"sliderBorder" : "1px solid rgba(128, 128, 128, 0.7)",
				"sliderColor" : "rgba(23, 23, 23, 1)",
				"sliderGradient" : "none",
				"slowBackward" : false,
				"slowForward" : true,
				"spacing" :
				{
					"all" : 2,
					"time" : 6,
					"volume" : 8
				},
				"stop" : false,
				"time" : true,
				"timeBgColor" : "rgba(0, 0, 0, 0)",
				"timeBgHeightRatio" : 1.2,
				"timeBorder" : "0px solid rgba(0, 0, 0, 0.3)",
				"timeBorderRadius" : 20,
				"timeColor" : "#ffffff",
				"timeFontSize" : 12,
				"timeSeparator" : " ",
				"tooltipColor" : "rgba(255, 255, 255, 1)",
				"tooltipTextColor" : "rgba(51, 51, 51, 1)",
				"tooltips" :
				{
					"buttons" : true,
					"fullscreen" : "Fullscreen",
					"fullscreenExit" : "Exit fullscreen",
					"marginBottom" : 5,
					"mute" : "Mute",
					"next" : "Next",
					"pause" : "Pause",
					"play" : "Play",
					"previous" : "Previous",
					"scrubber" : true,
					"slowMotionBwd" : "Slow backward",
					"slowMotionFBwd" : "Fast backward",
					"slowMotionFFwd" : "Fast forward",
					"slowMotionFwd" : "Slow forward",
					"stop" : "Stop",
					"unmute" : "Unmute",
					"volume" : true
				},
			   
				"volume" : true,
				"volumeBarHeightRatio" : 0.80000000000000004,
				"volumeBorder" : "1px solid rgba(128, 128, 128, 0.7)",
				"volumeColor" : "rgba(0, 153, 255, 1)",
				"volumeSliderColor" : "rgba(51, 51, 51, 1)",
				"volumeSliderGradient" : "none",
				"volumeSliderHeightRatio" : 0.40000000000000002,
				"width" : "100pct",
				"zIndex" : 1
			}
			
		}
	
	});
</script>