<div class="wrapper">
    <div class="all">
        <div class="hb-playlist-top">
            <div class="hb-section-header" style="border-bottom: solid 1px #000">
                Listado de playlist
            </div>
            <div class="hb-section-tips">
                Program Tip
            </div>
        </div>
        <div class="hb-playlist-content">
            <div class="hb-playlist-menu">
                <div id="path" class="hb-playlist-path">Default</div>
                <div class="hb-playlist-menu-btn">
                    <?php if(!empty($this->acl->resources["admin-playlist-btn-save"])):
                    ?>
                    <img src="images/program/btn_save.png" alt="save" id="saveBtn" />
                    <?php endif;?>
                    <?php if(!empty($this->acl->resources["admin-playlist-btn-delete"])):
                    ?>
                    <img src="images/program/btn_delete.png" alt="delete" id="deleteBtn"/>
                    <?php endif;?>
                    <?php if(!empty($this->acl->resources["admin-playlist-btn-add"])):
                    ?>
                    <img src="images/program/btn_playlist.png" alt="new" id="newBtn"/>
                    <?php endif;?>
                </div>
            </div>
            <div class="clear"></div>
            <div class="hb-playlist-left">
                <div class="hb-playlist-left-table" id="program-left-table"></div>
            </div>
            <div class="hb-playlist-right">
                <div class="hb-playlist-right-tabs">
                    <?php if(!empty($this->acl->resources["admin-playlist-tab-general"])):
                    ?>
                    <div id="tabGeneral" class=".hb-playlist-right-tabs-Sel">
                        <img src="images/program/tabicon_info.png" alt="general"/>
                        GENERAL
                    </div>
                    <?php endif;?>
                    <?php if(!empty($this->acl->resources["admin-playlist-tab-metadata"])):
                    ?>
                    <div id="tabMetadatas" class=".hb-playlist-right-tabs-nSel">
                        <img src="images/program/tabicon_info.png" alt="metadatas"/>
                        METADATAS
                    </div>
                    <?php endif;?>
                    <?php if(!empty($this->acl->resources["admin-playlist-tab-asset"])):
                    ?>
                    <div id="tabAssets" class=".hb-playlist-right-tabs-nSel">
                        <img src="images/program/tabicon_assets.png" alt="assets"/>
                        ASSETS
                    </div>
                    <?php endif;?>
                    <div class="clear"></div>
                </div>
                <div class="hb-playlist-right-form">
                    <?php echo $this->render('playlist/form/general.phtml');?>
                    <div class="clear"></div>
                    <?php echo $this->render('playlist/form/asset.phtml');?>
                    <div class="clear"></div>
                    <?php echo $this->render('playlist/form/metadata.phtml');?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <div id="newPlaylistDialog" title="Add new Playlist" class="jDialog">
            <form id="newPlaylistForm" method="POST" enctype="application/json">
                <div class="line">
                    <label for="playlistName" class="line-lbl">
                        Name
                    </label>
                    <input type="text" name="playlistName" id="playlistName" />
                </div>
                <div class="line">
                    <label for="playlistTitle" class="line-lbl">
                        Title
                    </label>
                    <input type="text" name="playlistTitle" id="playlistTitle" />
                </div>
                <div class="line">
                    <label for="playlistDesc" class="line-lbl">
                        Description
                    </label>
                    <textarea id="playlistDesc" name="playlistDesc" cols="50" rows="4"></textarea>
                </div>
                <div class="line">
                    <label for="playlistCombo" class="line-lbl">
                        Parent
                    </label>
                    <select id="playlistCombo" class="combo" name="playlistCombo" ></select>
                </div>
            </form>
        </div>
        <div id="playlistDeleteDialog" title="Delete Playlists?" class="jDialog">
            <p>
                <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>The selected playlist and its children will be . Are you sure?
            </p>
        </div>
        <div id="playlistUpdateDialog" title="Update Playlists" class="jDialog">
            <p>
                <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>The update operation was a success. Click accept to continue.
            </p>
        </div>
        <div id="removeAssetDialog" title="Remove Asset from playlists" class="jDialog">
            <p>
                <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This items will be permanently deleted and cannot be recovered. Are you sure?.
            </p>
        </div>
    </div>
</div>
<script type="text/javascript" charset="UTF-8">
    $(document).ready(function() {
        HB2.admin.playlist.init();
        HB2.admin.playlist.load();
    });

</script>
