<div class="hb-footer" >
    <div class="hb-footer-content" >
        <div class="hb-footer-content-left" >
            Online Video Platform | Welcome to HyperVideo
        </div><!-- cierre footer-content-left -->
        <div class="hb-footer-content-center" >
            2011 DIGITAL NOVAE MEDIA
        </div><!-- cierre footer-content-center -->
        <div class="hb-footer-content-right" >
            <a href="https://www.dnovae.com" target="_blank"><img src="<?php echo $this->staticRepo;?>/img/footer/dnovae.jpg"></img></a>
        </div><!-- cierre footer-content-right -->
    </div><!-- cierre footer-content -->
</div><!-- cierre footer -->