<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
        <title>Hollybyte Upload</title>
        <style type="text/css">
            body {
                font-family: Verdana, Geneva, sans-serif;
                font-size: 13px;
                color: #333;
                background: url(/css/plupload/img/bg.jpg);
            }
            .loading-wrapper {
                border: none;
                /*position: absolute;*/
                height: 99%;
                width: 99%;
                background: #FFF;
                position: absolute;
                filter: alpha(opacity=80);
                opacity: .8;
                left: 0px;
                top: 0px;
            }
            .loading {
                position: absolute;
                border: none;
                filter: alpha(opacity=90);
                opacity: .9;
                text-align: center;
                vertical-align: middle;
                left: 50%;
                top: 50%;
                width: 75px;
                height: 58px;
                z-index: 100;
            }
        </style>
        <link rel="stylesheet" href="/css/plupload/jquery.plupload.queue.css" type="text/css" media="screen"/>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
        <script type="text/javascript" src="/js/plupload/plupload.js"></script>
        <script type="text/javascript" src="/js/plupload/plupload.flash.js"></script>
        <script type="text/javascript" src="/js/plupload/plupload.html4.js"></script>
        <script type="text/javascript" src="/js/plupload/plupload.html5.js"></script>
        <script type="text/javascript" src="/js/plupload/jquery.plupload.queue.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $('#loading-wrapper')
                .hide()  // hide it initially
            });

        </script>
        <?php echo $this->headScript();?>
    </head>
    <body>
        <?php echo $this->layout()->content;?>
        <div id="loading-wrapper" class="loading-wrapper">
            <div id="loading" class="loading">
                <img src="<?php echo $this->staticRepo;?>/img/common/loader.gif" />
            </div><!--cierre loading-->
        </div>
    </body>
</html>