<div class="hb-assetform-tabTable-general" id="tabGeneralContent">
    <div class="hb-assetform-tabTable-general-left">
        <div class="hb-assetform-tabTable-general-right-half">
            <div class="hb-assetform-tabTable-general-right-info-title">
                CREATED
            </div>
            <div class="hb-assetform-tabTable-general-right-info-lbl2">
                <input class="hb-assetform-tabTable-general-right-half-input" type="text" name="assetCreated" id="assetCreated" />
            </div>
        </div>
        <div class="hb-assetform-tabTable-general-right-half">
            <div class="hb-assetform-tabTable-general-right-info-title">
                UPDATED
            </div>
            <div class="hb-assetform-tabTable-general-right-info-lbl2">
                <input class="hb-assetform-tabTable-general-right-half-input" type="text" name="assetUpdated" id="assetUpdated" />
            </div>
        </div>
        <div class="hb-assetform-tabTable-general-right-info">
            <div class="hb-assetform-tabTable-general-right-info-title">
                ID
            </div>
            <div class="hb-assetform-tabTable-general-right-info-lbl2">
                <span id="assetId"></span>
            </div>
            <a class="hb-assetform-tabTable-general-right-info-help"></a>
        </div>
        <div class="hb-assetform-tabTable-general-right-formbox">
            <div class="hb-assetform-tabTable-general-right-formbox-lbl">
                <span class="gwt-InlineHTML">NAME*</span>
            </div>
            <input class="hb-form-field-input" type="text" name="assetName" value="" id="assetName"/>
        </div>
        <div class="hb-assetform-tabTable-general-right-formbox">
            <div class="hb-assetform-tabTable-general-right-formbox-lbl">
                <span class="gwt-InlineHTML">TITTLE*</span>
            </div>
            <input class="hb-form-field-input" type="text" name="assetTitle" value="" id="assetTitle"/>
        </div>
        <div class="hb-assetform-tabTable-general-right-formbox">
            <div class="hb-assetform-tabTable-general-right-formbox-lbl">
                <span class="gwt-InlineHTML">DESCRIPTION*</span>
            </div>
            <textarea class="hb-form-field-textarea" name="assetDescription" id="assetDescription"></textarea>
        </div>
    </div><!-- cierre assetEdit-tabTable-general-right -->
    
    <div class="hb-assetform-tabTable-general-right">
        <div class="clear"></div>
            <input type="hidden" id="assetSplash" />
            <div class="hb-assetform-tabTable-general-left-img">
                <a id="assetPlayer" style="display:block;width:100%;height:100%;">
                <img  id="playerSplash" class="player-splash" />
                <img src="<?php echo $this->staticRepo;?>/images/common/play.png" alt="Play" class="player-play" />
                </a>
            </div>
            <div class="hb-assetform-tabTable-general-left-greybox">
                <div class="hb-assetform-tabTable-general-left-newthumbnail-lbl">
                    CHOOSE FRAME
                    <img src="<?php echo $this->staticRepo;?>/images/assetedit/btn_thumbnail.png" id="assetSnapshot"/>
                </div>
            </div>
            <div class="hb-assetform-tabTable-general-left-or">
                OR
            </div>
            <div class="hb-assetform-tabTable-general-left-greybox">
                <div class="hb-assetform-tabTable-general-left-newthumbnail-lbl">
                    UPLOAD THUMB
                    <img src="<?php echo $this->staticRepo;?>/images/assetedit/btn_thumbnail_upload.png" id="assetSnapshot"/>
                </div>
                <!-- <div style="display:none;">
                <input id="assetSplashUpload" name="assetSplashUpload" size="40" type="file" />
                <input id="assetSplashValue" name="assetSplashValue" type="hidden" />
                <input class="submit" type="submit" name="assetSplashUploadBtn" id="assetSplashUploadBtn" value="Send"/>
                </div>-->
            </div>
        </div>
    </div><!-- cierre assetEdit-tabTable-general -->
