<div style="display: none;" class="hb-assetform-tabTable-tags" id="tabTagsContent">
    <div  class="hb-assetform-tabTable-tagsGroup">
        <div class="hb-assetform-tabTable-tags-title">
            <img src="/images/assetedit/ico_tags.png"/>
            TAGS
        </div>
        <div class="hb-assetform-tabTable-tags-add">
            <input type="hidden" id="assetTags" />
            <input class="hb-assetform-tabTable-tags-add-txt" type="text" id="assetTag" />
            <button class="hb-assetform-tabTable-tags-add-btn" type="button" id="assetTagAdd" />
            </button>
        </div>
        <div class="hb-assetform-tabTable-tags-info">
            Comma separated. Limit to 32
            characters each, 20 tags max.
        </div>
        <div class="hb-assetform-tabTable-tags-list" id="assetTagList">
        </div><!-- cierre assetEdit-tabTable-tags-list -->
        <div class="clear">
        </div>
    </div>
    <hr>
    <div class="hb-assetform-tabTable-tagsGroup">
        <div class="hb-assetform-tabTable-tags-title">
            <img src="/images/assetedit/ico_tags.png"/>
            CATEGORIES
        </div>
        <div class="hb-assetform-tabTable-tags-add">
            <input type="hidden" id="assetCategories" />
            <input class="hb-assetform-tabTable-tags-add-txt" type="text" id="assetCategory" />
            <button class="hb-assetform-tabTable-tags-add-btn" type="button" id="assetCategoryAdd" />
            </button>
        </div>
        <div class="hb-assetform-tabTable-tags-info">
            Comma separated. Limit to 32
            characters each, 20 tags max.
        </div>
        <div class="hb-assetform-tabTable-tags-list" id="assetCategoryList">
        </div><!-- cierre assetEdit-tabTable-tags-list -->
        <div class="clear">
        </div>
    </div>
</div>
