<div style="display: none;" class="hb-assetform-tabTable-tabs" id="tabYoutubeContent">
    <div class="hb-assetform-youtube-header">
        <div class="hb-assetform-tabTable-metadata-header assetEdit-tabTable-metadata-header-title">
            <img src="/images/assetedit/ico_metadata.png" class="hb-assetform-tabTable-metadata-header-title-ico" alt="Image" />
            <div class="hb-assetform-tabTable-metadata-header-title-lbl"> YOUTUBE </div>
            <a class="hb-assetform-tabTable-metadata-header-title-help"></a>
        </div>
        <div class="hb-assetform-tabTable-metadata-header-right">
            <img src="/images/assetedit/buttons/youtube_btn.png" id="youtubeAddVideo"/>
        </div>
    </div>
    <div class="clear"></div>
    <br />
    <br />
    <div class="hb-assetform-youtube-content">
        <span class="hb-assetform-tabTable-metadata-header-title-lbl">VIDEO ID: </span>
        <span id="videoID"></span>
        <br />
        <br />
        <span class="hb-assetform-tabTable-metadata-header-title-lbl">Connector: </span>
        <div id="youtubeConnector">
            <span id="videoConnector"></span>
        </div>
        <br />
        <span class="hb-assetform-tabTable-metadata-header-title-lbl">Category: </span>
        <div id="youtubeCategory">
            <span id="videoCategory"></span>
        </div>
    </div>
</div>
