<div class="program-right-tab-asset" id="tabAssetContent">
    <div class="program-right-table" >
        <div class="program-right-menuTable">
            <div class="program-right-menuTable-label"> LISTADO DE ASSETS</div>
            <div class="program-right-menuTable-action">
                <button class="program-right-menuTable-add" type="button" id="add-asset-button"></button>
            </div>
            <div class="program-right-menuTable-move">
                <button id="btn-top" class="program-right-menuTable-move-top" type="button"></button>
                <button id="btn-up" class="program-right-menuTable-move-up" type="button"></button>
                <button id="btn-down" class="program-right-menuTable-move-down" type="button"></button>
                <button id="btn-bottom" class="program-right-menuTable-move-bottom" type="button"></button>
            </div>
            <table class="display dataTable" border="0" cellpadding="0" cellspacing="0" id="assetTable">
                <thead>
                    <tr>
                        <th style="width: 10px; text-align: center;"></th>
                        <th style="width: 90px; text-align: center;"></th>
                        <th style="width: 450px; text-align: center;"></th>
                        <th style="width: 10px; text-align: center;"></th>
                        <th style="width: 10px; text-align: center;"></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div id="addAssetDialog" title="Add Asset" class="jDialog">
    <table class="display dataTable" border="0" cellpadding="0" cellspacing="0" id="addAssetTable">
        <thead>
            <tr>
                <th style="width: 20px; text-align: center"></th>
                <th style="width: 60px; text-align: center"></th>
                <th style="width: 600px; text-align: center"></th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>