<div id="popupAddMeta" class="metavaluesWindow"  style="display:none">
	        <table class="c21" cellpadding="0" cellspacing="0">
	          <tbody>
	            <tr class="dialogTop">
	              <td class="dialogTopLeft">
	                <div class="dialogTopLeftInner"></div>
	              </td>
	              <td class="dialogTopCenter">
	                <div class="dialogTopCenterInner Caption c20">
	                  ADD META
	                </div>
	              </td>
	              <td class="dialogTopRight">
	                <div class="dialogTopRightInner"></div>
	              </td>
	            </tr>
	            <tr class="dialogMiddle">
	              <td class="dialogMiddleLeft">
	                <div class="dialogMiddleLeftInner"></div>
	              </td>
	              <td class="dialogMiddleCenter">
	                <div class="dialogMiddleCenterInner dialogContent GFR5ENXDMK">
	                  <div class="GFR5ENXDOK">
	                    <div class="GFR5ENXDNK">
	                      Name:
	                    </div><input class="GFR5ENXDAL" type="text" />
	                  </div>
	                  <div class="GFR5ENXDOK">
	                    <div class="GFR5ENXDNK">
	                      Type:
	                    </div><select class="GFR5ENXDPK">
	                      <option value="STRING">
	                        STRING
	                      </option>
	                      <option value="INTEGER">
	                        INTEGER
	                      </option>
	                      <option value="DOUBLE">
	                        DOUBLE
	                      </option>
	                      <option value="COLOUR">
	                        COLOUR
	                      </option>
	                      <option value="URL">
	                        URL
	                      </option>
	                      <option value="FILE">
	                        FILE
	                      </option>
	                      <option value="BOOLEAN">
	                        BOOLEAN
	                      </option>
	                    </select>
	                  </div>
	                  <div class="GFR5ENXDOK">
	                    <div class="GFR5ENXDNK">
	                      Value:
	                    </div>
	                    <div class="GFR5ENXDPK">
	                      <input class="GFR5ENXDAL" type="text" />
	                    </div>
	                  </div>
	                  <div class="GFR5ENXDOK">
	                    <button class="gwt-Button" type="button">Save</button> <button class=
	                    "gwt-Button" type="button">Cancel</button>
	                  </div>
	                </div>
	              </td>
	              <td class="dialogMiddleRight">
	                <div class="dialogMiddleRightInner"></div>
	              </td>
	            </tr>
	            <tr class="dialogBottom">
	              <td class="dialogBottomLeft">
	                <div class="dialogBottomLeftInner"></div>
	              </td>
	              <td class="dialogBottomCenter">
	                <div class="dialogBottomCenterInner"></div>
	              </td>
	              <td class="dialogBottomRight">
	                <div class="dialogBottomRightInner"></div>
	              </td>
	            </tr>
	          </tbody>
	        </table>
	      </div>