<div id="popupAddSubtitle" class="metavaluesWindow" style="display:none">
	        <table class="" cellpadding="0" cellspacing="0">
	          <tbody>
	            <tr class="dialogTop">
	              <td class="dialogTopLeft">
	                <div class="dialogTopLeftInner"></div>
	              </td>
	              <td class="dialogTopCenter">
	                <div class="dialogTopCenterInner Caption c20">
	                  Subtitle
	                </div>
	              </td>
	              <td class="dialogTopRight">
	                <div class="dialogTopRightInner"></div>
	              </td>
	            </tr>
	            <tr class="dialogMiddle">
	              <td class="dialogMiddleLeft">
	                <div class="dialogMiddleLeftInner"></div>
	              </td>
	              <td class="dialogMiddleCenter">
	                <div class="dialogMiddleCenterInner dialogContent GFR5ENXDMK">
	                  <div class="GFR5ENXDOK">
	                    <div class="GFR5ENXDNK">
	                      Lang:
	                    </div><select class="GFR5ENXDPK">
	                      <option value="es">
	                        Spanish
	                      </option>
	                      <option value="en">
	                        English
	                      </option>
	                    </select>
	                  </div>
	                  <div class="GFR5ENXDOK">
	                    <div class="GFR5ENXDNK">
	                      File:
	                    </div>
	                    <table class="GWTUpld" cellpadding="0" cellspacing="0">
	                      <tbody>
	                        <tr>
	                          <td class="c3" align="left">
	                            <form action="servlet.gupld" method="post" enctype=
	                            "multipart/form-data" target="FormPanel_Aquilae_3">
	                              <div class="upld-form-elements">
	                                <input name="GWTU-01577333872711707" size="40" class=
	                                "gwt-FileUpload" type="file" /> <button class="gwt-Button submit"
	                                type="button">Send</button>
	                              </div>
	                            </form>
	                          </td>
	                          <td class="c3" align="left">
	                            <table class="upld-status c4" cellpadding="0" cellspacing="0">
	                              <tbody>
	                                <tr>
	                                  <td class="c3" align="left">
	                                    <div class="cancel"></div>
	                                  </td>
	                                  <td class="c3" align="left">
	                                    <div class="filename"></div>
	                                  </td>
	                                  <td class="c3" align="left">
	                                    <div class="status"></div>
	                                  </td>
	                                </tr>
	                              </tbody>
	                            </table>
	                          </td>
	                        </tr>
	                      </tbody>
	                    </table>
	                  </div>
	                  <div class="GFR5ENXDOK">
	                    <button class="gwt-Button" type="button">Save</button> <button class=
	                    "gwt-Button" type="button">Cancel</button>
	                  </div>
	                </div>
	              </td>
	              <td class="dialogMiddleRight">
	                <div class="dialogMiddleRightInner"></div>
	              </td>
	            </tr>
	            <tr class="dialogBottom">
	              <td class="dialogBottomLeft">
	                <div class="dialogBottomLeftInner"></div>
	              </td>
	              <td class="dialogBottomCenter">
	                <div class="dialogBottomCenterInner"></div>
	              </td>
	              <td class="dialogBottomRight">
	                <div class="dialogBottomRightInner"></div>
	              </td>
	            </tr>
	          </tbody>
	        </table>
</div>