<div class="wrapper">
    
    <div class="hb-asset-assetMenu">
        <div class="hb-asset-assetMenu-content">
            <div class="hb-asset-assetMenu-refresh" id="assetRefresh">
                <label>
                    ASSETLIST
                </label>
                <img src="<?php echo $this->staticRepo;?>/img/assetlist/refresh.png">
            </div>

            <?php if(!empty($this->acl->resources["admin-asset-list-deploy"])):?>
            <div class="hb-asset-assetMenu-deploy" id="assetDeploy">
                <label>
                    DEPLOY
                </label>
                <img src="<?php echo $this->staticRepo;?>/img/assetlist/deploy.png">
            </div>
            <?php endif; ?>
            <div class="hb-asset-assetMenu-search">
                <div class="hb-asset-assetMenu-search-box">
                    <input class="hb-asset-assetMenu-search-box-txt" type="text" id="inputSearch"/>
                    <div class="hb-asset-assetMenu-search-box-clear">
                    </div>
                </div>
                <div class="hb-asset-assetMenu-search-btn">
                </div>
            </div>
        </div>
    </div>

    <div class="all">
        <ul class="hb-asset-list" id="assetlist">
            
        </ul>

        <div class="clear">
        </div>
        
        <div class="hb-asset-tablecontent">
            
        </div>

    </div>

    <div class="hb-asset-bottomContent">
        <div class="hb-asset-bottom">
            <div class="hb-asset-bottom-create">
                <img
                src="<?php echo $this->staticRepo;?>/img/assetlist/icon_light.png"
                class="hb-asset-bottom-create-img">
                Crea tu playlist en la sección
                <u>
                    program
                </u>
            </div>
            <div style="visibility: hidden;" class="hb-asset-pagination">
                <div class="hb-asset-pagination-prev">
                </div>
                <div class="hb-asset-pagination-info">
                    <div class="hb-asset-pagination-info-current" id="paginationCurrentPos">
                        1
                    </div>
                    <div>
                        de 1
                    </div>
                </div>
                <div class="hb-asset-pagination-next">
                </div>
            </div><!--cierre hb-asset-pagination-->
            <div class="hb-asset-bottom-help">
                <img
                src="<?php echo $this->staticRepo;?>/img/assetlist/icon_question.png"
                class="hb-asset-bottom-help-question">
                ADD LIVE CONNECTION
                <img
                src="<?php echo $this->staticRepo;?>/img/assetlist/icon_addlive.png"
                class="hb-asset-bottom-help-addlive">
            </div>
        </div><!--cierre hb-asset-bottom-help-->
        <div class="clear">
        </div>
    </div><!--cierre hb-asset-bottomContent-->
    
</div><!-- cierre wrapper -->

<div id="assetlistPlayer">
    
    <a id="player" style="display:block;width:100%;height:100%;">
    </a>
</div><!--cierre assetlistPlayer-->
<div id="assetlistEmbedDialog">
     <textarea class="form-field-textarea" id="txtEmbed" style="width:100%; height:160px;"></textarea>
</div>

<div id="assetlistDeleteDialog">
</div>

<script type="text/javascript">
    $(document).ready( function() {
        // Init Delete Value Dialog
        $('#assetlistPlayer').dialog({
            autoOpen: false,
            resizable: false,
            width: 850,
            height: 600,
            closeText: 'close',
            modal: true,
            title:true

        });
    });
    $( "#assetlistPlayer" ).dialog( "option", "dialogClass", 'assetlistPlayer' );
    
    $('#assetlistEmbedDialog').dialog({
                autoOpen: false,
                resizable: false,
                width: 850,
                height: 280,
                closeText: 'close',
                modal: true,
                title:false

        });
        $( "#assetlistEmbedDialog" ).dialog( "option", "dialogClass", 'assetlistEmbedDialog' );
        
        
        asset = new Scripts_AssetList('assetlist', <?php echo json_encode($this->account);?>);
        asset.assetDeleteDialog = $('#assetlistDeleteDialog');
        asset.appendAll();
        
        
        
        //CREANDO ASSET TABLE.
        
        /*assetlistable = $('#assetTable').dataTable({
            "bLengthChange" : false,
            "aoColumnDefs" : [{
                "fnRender" : function(oObj) {
                    return HB2.admin.metavalue.renderizeMetavalue(oObj.aData[1], oObj.aData[2])
                    //return 'valor: '+ oObj.aData[2];
                },
                "aTargets" : [3]
            }, {
                "bVisible" : false,
                "aTargets" : [2]
            }, {
                "sClass" : "center",
                "aTargets" : [3]
            }, {
                "sClass" : "center",
                "aTargets" : [4]
            }]
        });
        
        function getAssetData(objs) {
            var datas = new Array();
            for(i in objs) {
                var data = new Array();
                data[0] = objs[i].name;
                data[1] = objs[i].type;
                data[2] = objs[i].format;
                data[3] = objs[i].path;
                //data[4] = renderAssetContentAction();
                datas[i] = data;
            }
            return datas;
        }
        
        //Como es esto?
        datas = getAssetData(objs);
        
        assetlistable.fnClearTable();
        assetlistable.fnAddData(datas);*/

</script>