<script src="/js/jquery/jquery.json-2.2.min.js" type="text/javascript"></script>
<script src="/js/jquery/jquery.iframe-post-form.min.js" type="text/javascript"></script>
<div class="all">
    <div class="assetEdit-tabTable-metadata-header">
        <div class="assetlist-assetMenu-refresh">
            <label>
                REFRESH
            </label>
            <img id="refresh" src="images/common/refresh.png" class="gwt-Image" />
        </div>
        <?php if(!empty($this->acl->resources["admin-connector-add"]) && (
                    (empty($this->acl->resources["admin-connector-add"]) ) ||
                    (!empty($this->acl->resources["admin-connector-add"]) 
                        && count($this->entity) < $this->acl->resources["admin-connector-limit"] ) ) ):?> 
        <button id="add" class="connectorlist-header-add" type="button">
        </button>
        
        <?php endif;?>
    </div><!-- cierre assetEdit-tabTable-metadata-header -->
    <table id="connectorTable" class="display dataTable" border="0" cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th style="width: 200px;" class="sorting">NAME</th>
                <th style="width: 50px;" class="sorting">TYPE</th>
                <th style="width: 200px;" class="sorting">DESC</th>
                <th style="width: 200px;" class="sorting">DATE</th>
                <th style="width: 100px;" class="sorting">EDIT/DELETE</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    <div class="clear"></div>
</div><!-- cierre all -->
<div id="deleteDialog" title="Delete Connector?">
    <p>
        <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>These items will be permanently deleted and cannot be recovered. Are you sure?
    </p>
</div>
<script type="text/javascript" charset="utf-8">
    function onClickEditConnector(element, table) {
        var id = table.fnGetData($(element).parents('tr')[0])[0];
        window.location = '/connector/form?id='+id;
    }

    function onClickDeleteConnector(element, table) {
        var pos = table.fnGetPosition($(element).parents('tr')[0]);
        var data = table.fnGetData(pos);
        $(table).data('position', pos);
        $(table).data('data', data);
        $("#deleteDialog").dialog('open');
    }

    function initConnectorsTable(table, objs) {
        table.fnClearTable();
        var rows = new Array();
        for (var i = 0; i < objs.length; i++) {
            var row = new Array();
            row[0] = objs[i].id;
            if (objs[i].type == 'FTP') {
                row[1] = '<img src="/images/connector/ftp.png" />';
            } else if (objs[i].type == 'YOUTUBE') {
                row[1] = '<img src="/images/connector/youtube.png" />';
            } else if (objs[i].type == 'TWITTER') {
                row[1] = '<img src="/images/connector/twitter.png" />';
            } else if (objs[i].type == 'FACEBOOK') {
                row[1] = '<img src="/images/connector/facebook.png" />';
            }
            row[2] = objs[i].description;
            row[3] = objs[i].created;
            row[4] = '<img class="connector-edit" src="/images/common/edit.png" /><img class="connector-delete" src="/images/common/delete.png"/>';
            rows[i] = row;
        }
        table.fnAddData(rows);

        $('.connector-edit').click( function() {
            onClickEditConnector(this, table);
        });
        $('.connector-delete').click( function() {
            onClickDeleteConnector(this, table);
        });
    }

    function loadConnectors(table) {
        $.ajax({
            url: '/connector/find',
            dataType: 'json',
            success: function(data, textStatus, jqXHR) {
                initConnectorsTable(table, data.result);
            }
        } );
    }

    function deleteConnector(id) {
        console.log('deleteConnector: '+id);
        $.ajax({
            url: '/connector/delete?id='+id,
            dataType: 'json',
            success: function(data, textStatus, jqXHR) {
            }
        } );
    }

    $(document).ready( function() {
        // Init Connectors Table
        var table = $('#connectorTable').dataTable({
            "bLengthChange": false,
            "aoColumnDefs": [{
                "sClass": "center",
                "aTargets": [ 1, 3, 4 ]
            }]
        });

        // Init Delete Dialog
        $('#deleteDialog').dialog({
            autoOpen: false,
            resizable: false,
            height:140,
            modal: true,
            buttons: {
                "Delete item": function() {
                    var pos = table.data('position');
                    var data = table.data('data');
                    deleteConnector(data[0]);
                    table.fnDeleteRow(pos);
                    $(this).dialog("close");
                },
                Cancel: function() {
                    $(this).dialog("close");
                }
            }
        });

        // Refresh Connectors Button
        $('#refresh').click( function() {
            loadConnectors(table);
        });
        // Add Connector Button
        $('#add').click( function() {
            window.location = '/connector/form';
        });
        // Load Connectors
        loadConnectors(table);
    });
</script>